package initconfig

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/ricardo/anthrogo/internal/config"
	"github.com/ricardo/anthrogo/pkg/permissions"
)

// Run launches the interactive wizard. in/out are stdin/stdout (overridable
// for tests). settingsPath is where to write. If file exists and !force,
// return an error describing the conflict.
func Run(in io.Reader, out io.Writer, settingsPath string, force bool) error {
	if !force {
		if _, err := os.Stat(settingsPath); err == nil {
			return fmt.Errorf("settings file already exists at %s (re-run with --force to overwrite)", settingsPath)
		}
	}

	reader := bufio.NewReader(in)
	cfg := defaultsCfg()

	fmt.Fprintln(out, "anthrogo init-config — let's set up your settings.yaml")
	fmt.Fprintln(out, "(press Enter to accept the default in [brackets])")
	fmt.Fprintln(out, "")

	// Provider selection
	provider := ask(reader, out, "Default provider [anthropic]: ", "anthropic")
	cfg.Provider = provider

	// Model selection
	defaultModel := suggestedModel(provider)
	cfg.Model = ask(reader, out, fmt.Sprintf("Default model [%s]: ", defaultModel), defaultModel)

	// API key source
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "API key: how should anthrogo find it?")
	fmt.Fprintln(out, "  1) Env var (recommended) — set ANTHROPIC_API_KEY in your shell")
	fmt.Fprintln(out, "  2) Inline in YAML — convenient but the file holds a secret")
	fmt.Fprintln(out, "  3) Use /login OAuth flow later")
	choice := ask(reader, out, "Choice [1]: ", "1")
	switch strings.TrimSpace(choice) {
	case "2":
		key := ask(reader, out, "Enter API key (will be saved verbatim): ", "")
		cfg.APIKey = key
	case "3":
		// No api_key field; user runs /login later
	default:
		cfg.APIKey = "env:" + apiKeyEnvVar(provider)
	}

	// Permission mode
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "Permission mode:")
	fmt.Fprintln(out, "  - default      (ask before each non-allowlisted tool)")
	fmt.Fprintln(out, "  - acceptEdits  (Write/Edit/NotebookEdit allowed automatically)")
	fmt.Fprintln(out, "  - plan         (read-only; for planning before edits)")
	mode := ask(reader, out, "Mode [default]: ", "default")
	cfg.Mode = permissions.Mode(strings.TrimSpace(mode))

	// Optional features
	fmt.Fprintln(out, "")
	if askYesNo(reader, out, "Enable telemetry (opt-in, anonymous)?", false) {
		cfg.Telemetry.Enabled = true
		cfg.Telemetry.Endpoint = ask(reader, out, "Telemetry endpoint URL: ", "")
	}

	autoCompactStr := ask(reader, out, "Auto-compact threshold (input+output tokens; 0 = disabled) [0]: ", "0")
	fmt.Sscanf(autoCompactStr, "%d", &cfg.AutoCompactThreshold)

	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "Skipping MCP servers / hooks / plugins (configure later manually or via /mcp, /hook, /plugin).")
	fmt.Fprintln(out, "")

	// Marshal + write
	if err := os.MkdirAll(filepath.Dir(settingsPath), 0o755); err != nil {
		return err
	}
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return err
	}
	header := "# anthrogo settings.yaml — generated by `anthrogo init-config`\n# Edit freely; see README.md for full schema.\n\n"
	if err := os.WriteFile(settingsPath, []byte(header+string(data)), 0o600); err != nil {
		return err
	}
	fmt.Fprintf(out, "Wrote %s\n", settingsPath)
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "Next:")
	fmt.Fprintln(out, "  1) Run `anthrogo doctor` to verify environment")
	fmt.Fprintln(out, "  2) Run `anthrogo` to start the TUI")
	return nil
}

func defaultsCfg() config.Config {
	return config.Config{Provider: "anthropic", Model: "claude-sonnet-4-6", Mode: permissions.ModeDefault}
}

func ask(r *bufio.Reader, out io.Writer, prompt, def string) string {
	fmt.Fprint(out, prompt)
	line, err := r.ReadString('\n')
	if err != nil {
		return def
	}
	line = strings.TrimRight(line, "\r\n")
	if line == "" {
		return def
	}
	return line
}

func askYesNo(r *bufio.Reader, out io.Writer, prompt string, def bool) bool {
	suffix := "[y/N]"
	if def {
		suffix = "[Y/n]"
	}
	ans := ask(r, out, prompt+" "+suffix+" ", "")
	ans = strings.ToLower(strings.TrimSpace(ans))
	if ans == "" {
		return def
	}
	return ans == "y" || ans == "yes"
}

func suggestedModel(provider string) string {
	switch provider {
	case "anthropic":
		return "claude-sonnet-4-6"
	case "deepseek":
		return "deepseek-chat"
	case "kimi":
		return "kimi-k2-0905-preview"
	case "minimax":
		return "MiniMax-M2"
	case "glm":
		return "glm-4.6"
	case "openai":
		return "gpt-4o"
	default:
		return "claude-sonnet-4-6"
	}
}

func apiKeyEnvVar(provider string) string {
	switch provider {
	case "anthropic":
		return "ANTHROPIC_API_KEY"
	case "deepseek":
		return "DEEPSEEK_API_KEY"
	case "kimi":
		return "KIMI_API_KEY"
	case "minimax":
		return "MINIMAX_API_KEY"
	case "glm":
		return "GLM_API_KEY"
	case "openai":
		return "OPENAI_API_KEY"
	default:
		return "ANTHROPIC_API_KEY"
	}
}
